### ISSUE TITLE
执行php artisan chemex:install错误

### ISSUE THREAD

**Issue by KeysBit** [celaraze/chemex#14]
所有输出为：
Deprecated: Return type of Illuminate\Support\Collection::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /root/chemex/vendor/laravel/framework/src/Illuminate/Collections/Collection.php on line 836

Deprecated: Return type of Illuminate\Support\LazyCollection::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /root/chemex/vendor/laravel/framework/src/Illuminate/Collections/LazyCollection.php on line 836

In Model.php line 25:

  During inheritance of JsonSerializable: Uncaught ErrorException: Return type of Illuminate\Database\Eloquent\Model:
  :jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[ReturnTypeWill
  Change] attribute should be used to temporarily suppress the notice in /root/chemex/vendor/laravel/framework/src/Il
  luminate/Database/Eloquent/Model.php:1429
  Stack trace:
  #0 /root/chemex/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(25): Illuminate\Foundation\Boot
  strap\HandleExceptions->handleError(8192, 'Return type of ...', '/root/chemex/ve...', 1429)
  #1 /root/chemex/vendor/composer/ClassLoader.php(480): include('/root/chemex/ve...')
  #2 /root/chemex/vendor/composer/ClassLoader.php(346): Composer\Autoload\includeFile('/root/chemex/ve...')
  #3 /root/chemex/vendor/laravel/framework/src/Illuminate/Database/DatabaseServiceProvider.php(42): Composer\Autoload
  \ClassLoader->loadClass('Illuminate\\Data...')
  #4 /root/chemex/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(672): Illuminate\Database\Databa
  seServiceProvider->register()
  #5 /root/chemex/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(75): Illuminate\Foundatio
  n\Application->register(Object(Illuminate\Database\DatabaseServiceProvider))
  #6 /root/chemex/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(649): Illuminate\Foundation\Prov
  iderRepository->load(Array)
  #7 /root/chemex/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterProviders.php(17): Illuminate\
  Foundation\Application->registerConfiguredProviders()
  #8 /root/chemex/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(237): Illuminate\Foundation\Boot
  strap\RegisterProviders->bootstrap(Object(Illuminate\Foundation\Application))
  #9 /root/chemex/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(310): Illuminate\Foundation\A
  pplication->bootstrapWith(Array)
  #10 /root/chemex/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(127): Illuminate\Foundation\
  Console\Kernel->bootstrap()
  #11 /root/chemex/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\A
  rgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
  #12 {main}

系统为Ubuntu 21.04,
$uname -a
Linux ecs-IDmC0 5.8.0-63-generic #71-Ubuntu SMP Tue Jul 13 15:59:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
$php --version
PHP 8.1.0alpha3 (cli) (built: Jul 29 2021 10:01:55) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.0-dev, Copyright (c) Zend Technologies

请问如何解决？

**Comment by celaraze** [comment]
数据库版本用的什么？

**Comment by KeysBit** [comment]
> 数据库版本用的什么？

MariaDB 10.5应该是，版本是满足readme要求的
